name: Publish Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Build distribution 📦
    runs-on: ngs

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    #- name: Store the distribution packages
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: python-package-distributions
    #    path: dist/

    - name: Create Release
      env:
        GH_HOST: "biogit.pri.bms.com"
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >-
        gh release create
        --generate-notes
        --draft
        --prerelease
        --repo ${{ github.repository }}
        ${{ github.ref }}
        dist/**
