name: Unit Test and Lint

on: [push]

jobs:
  test:
    runs-on: ngs

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mock

    - name: Test
      run: |
        pip install coverage
        coverage run -m pytest
      
    - name: Analysing the code with pylint
      run: |
        make lint
