name: Pylint

on: [push]

jobs:
  build:
    runs-on: ngs
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint sevenbridges-python arvados-python-client
    - name: Analysing the code with pylint
      run: |
        pylint --max-line-length=120 --ignore-imports=y $(git ls-files '*.py')
