name: Unit Test and Lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-gnutls-dev libgnutls28-dev

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Test
      run: |
        PYTHONPATH=src coverage run --source=src -m pytest
        coverage report

    - name: Analysing the code with pylint
      run: |
        pylint --max-line-length=120 --ignore-imports=y --exit-zero $(git ls-files '*.py')
